import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconBrandGoogle,
  IconMap,
  IconStackFront,
  IconRecycle,
  IconBook2,
  IconCalendarMonth,
  IconClipboardCheck,
  IconCalendarClock
} from '@tabler/icons-react';
import {
  GroupIcon,
  WarehouseIcon,
  CogIcon,
  FactoryIcon,
  ListChecksIcon,
  UsersIcon
} from 'lucide-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  google: IconBrandGoogle,
  twitter: IconBrandTwitter,
  check: IconCheck,
  map: IconMap,
  stackFront: IconStackFront,
  recycle: IconRecycle,
  bookText: IconBook2,
  calendarDays: IconCalendarMonth,
  clipboardCheck: IconClipboardCheck,
  users: UsersIcon,
  userCircle: IconUserCircle,
  group: GroupIcon,
  fileText: IconFileText,
  calendarClock: IconCalendarClock,
  wareHouse: WarehouseIcon,
  cog: CogIcon,
  listCheck: ListChecksIcon,
  factory: FactoryIcon
};
